### ISSUE TITLE
TestFlight link in README does not work

### ISSUE THREAD

**Issue by habi** [iKenndac/Tofu#131]
The TestFlight link [added some time ago in the README](https://github.com/iKenndac/Tofu/commit/dde68739c0f4198f0d1c2a5fb0224eae97ce05f8) does not work.
![IMG_3538](https://user-images.githubusercontent.com/1651235/235601906-e5e9d56d-d5b6-4434-9b76-7102d8fede1d.jpeg)

**Comment by github2099** [comment]
The readme file had been updated to remove non-working testflight link
https://github.com/iKenndac/Tofu/commits/main/README.md
